language: python
python:
  - "2.7"

before_install:
  - sudo apt-get -y install python-pip python-dev g++ make libfreetype6-dev libpng-dev libopenblas-dev liblapack-dev gfortran r-base libssl-dev libreadline-dev
install:
  - pip install --quiet --use-mirrors numpy cython
  - pip install --use-mirrors --upgrade -r requirements.txt
  - pip install -e git+https://github.com/intuition-io/intuition.git@develop#egg=intuition
  - python setup.py install
  - pip install --use-mirrors --upgrade -r dev-requirements.txt

before_script:
  - pep8 --ignore E265 --exclude _review insights tests
script:
  - nosetests -w tests --with-coverage --cover-package=insights

branches:
  only:
    - master
    - develop
